version: "3.5"

services:
  app: 
    build:
      context: ./
      dockerfile: Dockerfile-app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file: 
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000

    depends_on: 
      - db_default

  db_default:
    image: "postgres:13.0"
    hostname: db
    environment:
      POSTGRES_PASSWORD: "db"
      POSTGRES_USER: "db"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    

  # server:
