version: "3.5"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-frontend
    volumes:
      - ./front-end/:/app
    ports:
      - "3000:3000"

    command: npm run start

  backend:
    build:
      context: ./server/
      dockerfile: Dockerfile-app
    volumes:
      - ./server/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db_default

  db_default:
    image: "postgres:13.0"
    hostname: db
    environment:
      POSTGRES_PASSWORD: "db"
      POSTGRES_USER: "db"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"

  # server:
