version: "3.5"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-frontend
    volumes:
      - ./front-end/:/app
    ports:
      - "3000:3000"

    command: npm run start-dev
    # networks:
    #   - main
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    volumes:
      - ./server/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    command: python manage.py runserver 0.0.0.0:8000
    # networks:
    #   - main

    depends_on:
      - db_default

  db_default:
    image: "postgres:13.0"
    hostname: db
    environment:
      POSTGRES_PASSWORD: "db"
      POSTGRES_USER: "db"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    # networks:
    #   - main

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9.7
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    # networks:
    #   - main
    ports:
      - "5672:5672"
    restart: on-failure

