FROM python:3.9.5

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update && apt-get install -y apt-xapian-index 

RUN mkdir /app
COPY requirements.txt /app


RUN pip install -r /app/requirements.txt

COPY ./ /app
WORKDIR /app

# ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
