# Generated by Django 3.2.4 on 2021-09-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='matches_draw',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
